import json

with open("cdragon_data/en_us.json", encoding="utf-8") as f:
    data = json.load(f)

traits_data: list = data["sets"]["13"]["traits"]
traits: list[str] = list(map(lambda trait: trait["name"], traits_data))

java_enum = f"""// Generated by "scripts/generate_tft_traits.py"

package com.tftrolldownsimulator.models.generated;

import java.util.Map;
import java.util.AbstractMap;

public enum Trait {"{"}
  {"\n  ".join([f'{trait.upper().replace(" ", "_").replace("-", "_")}("{trait}"){"," if i != len(traits) - 1 else ";"}' for i, trait in enumerate(traits)])}

  private static final Map<String, Trait> traitMap = Map.ofEntries(
      {"\n      ".join([f'new AbstractMap.SimpleEntry<>("{trait}", Trait.{trait.upper().replace(" ", "_").replace("-", "_")}){"," if i != len(traits) - 1 else ");"}' for i, trait in enumerate(traits)])}

  private static final Map<String, String> iconMap = Map.ofEntries(
      {"\n      ".join([f'new AbstractMap.SimpleEntry<>("{trait["name"]}", "{trait["apiName"] + ".png"}"){"," if i != len(traits_data) - 1 else ");"}' for i, trait in enumerate(traits_data)])}
  
  private final String trait;

  Trait(String trait) {"{"}
    this.trait = trait;
  {"}"}

  public String getValue() {"{"}
    return this.trait;
  {"}"}

  public static Trait fromString(String traitValue) {"{"}
    return Trait.traitMap.get(traitValue);
  {"}"}

  public String getLogo() {"{"}
    return Trait.iconMap.get(this.trait);
  {"}"}
{"}"}
"""

with open(
    "src/main/java/com/tftrolldownsimulator/models/generated/Trait.java", "w"
) as f:
    f.write(java_enum)
